# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "anope_cs_info", :id => false, :force => true do |t|
    t.column "ci_id", :integer, :null => false
    t.column "name", :string, :default => "", :null => false
    t.column "founder", :text, :default => "", :null => false
    t.column "successor", :text, :default => "", :null => false
    t.column "founderpass", :binary, :default => "", :null => false
    t.column "descr", :text, :default => "", :null => false
    t.column "url", :text, :default => "", :null => false
    t.column "email", :text, :default => "", :null => false
    t.column "time_registered", :integer, :limit => 10, :default => 0, :null => false
    t.column "last_used", :integer, :limit => 10, :default => 0, :null => false
    t.column "last_topic", :text, :default => "", :null => false
    t.column "last_topic_setter", :text, :default => "", :null => false
    t.column "last_topic_time", :integer, :limit => 10, :default => 0, :null => false
    t.column "flags", :integer, :limit => 10, :default => 0, :null => false
    t.column "forbidby", :text, :default => "", :null => false
    t.column "forbidreason", :text, :default => "", :null => false
    t.column "bantype", :integer, :limit => 6, :default => 0, :null => false
    t.column "accesscount", :integer, :limit => 6, :default => 0, :null => false
    t.column "akickcount", :integer, :limit => 6, :default => 0, :null => false
    t.column "mlock_on", :integer, :limit => 10, :default => 0, :null => false
    t.column "mlock_off", :integer, :limit => 10, :default => 0, :null => false
    t.column "mlock_limit", :integer, :limit => 10, :default => 0, :null => false
    t.column "mlock_key", :text, :default => "", :null => false
    t.column "mlock_flood", :text, :default => "", :null => false
    t.column "mlock_redirect", :text, :default => "", :null => false
    t.column "entry_message", :text, :default => "", :null => false
    t.column "memomax", :integer, :limit => 5, :default => 0, :null => false
    t.column "botnick", :string, :default => "", :null => false
    t.column "botflags", :integer, :limit => 10, :default => 0, :null => false
    t.column "bwcount", :integer, :limit => 6, :default => 0, :null => false
    t.column "capsmin", :integer, :limit => 6, :default => 0, :null => false
    t.column "capspercent", :integer, :limit => 6, :default => 0, :null => false
    t.column "floodlines", :integer, :limit => 6, :default => 0, :null => false
    t.column "floodsecs", :integer, :limit => 6, :default => 0, :null => false
    t.column "repeattimes", :integer, :limit => 6, :default => 0, :null => false
    t.column "active", :boolean, :default => true, :null => false
  end

  add_index "anope_cs_info", ["name"], :name => "name", :unique => true
  add_index "anope_cs_info", ["name"], :name => "name_index"

  create_table "anope_ns_core", :id => false, :force => true do |t|
    t.column "nc_id", :integer, :null => false
    t.column "display", :string, :default => "", :null => false
    t.column "pass", :binary, :default => "", :null => false
    t.column "email", :text, :default => "", :null => false
    t.column "icq", :integer, :limit => 10, :default => 0, :null => false
    t.column "url", :text, :default => "", :null => false
    t.column "flags", :integer, :default => 0, :null => false
    t.column "language", :integer, :limit => 5, :default => 0, :null => false
    t.column "accesscount", :integer, :limit => 6, :default => 0, :null => false
    t.column "memocount", :integer, :limit => 5, :default => 0, :null => false
    t.column "memomax", :integer, :limit => 5, :default => 0, :null => false
    t.column "channelcount", :integer, :limit => 5, :default => 0, :null => false
    t.column "channelmax", :integer, :limit => 5, :default => 0, :null => false
    t.column "greet", :text, :default => "", :null => false
    t.column "active", :boolean, :default => true, :null => false
  end

  add_index "anope_ns_core", ["display"], :name => "display", :unique => true
  add_index "anope_ns_core", ["display"], :name => "display_index"

  create_table "channels_feeds", :id => false, :force => true do |t|
    t.column "channel_id", :integer
    t.column "feed_id", :integer
  end

  create_table "feeds", :force => true do |t|
    t.column "name", :string
    t.column "all_channels", :boolean
    t.column "access_key", :string
    t.column "user_id", :integer
  end

  create_table "topics", :force => true do |t|
    t.column "topic", :string
    t.column "parsed_topic", :text
    t.column "user", :string
    t.column "created_at", :datetime
    t.column "access_key", :string
    t.column "channel_id", :integer
  end

end
